# Generated by Django 3.0.5 on 2020-04-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('MISC', 'Miscellaneous'), ('WEB DEVELOPMENT', 'Web Development'), ('PHOTO', 'Photo'), ('NEWS', 'News'), ('GAME', 'Game'), ('TEST', 'Test')], default='MISC', max_length=20),
        ),
    ]
