# Generated by Django 3.0.5 on 2020-04-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar_url',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
