# Generated by Django 3.0.5 on 2020-04-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
