# Generated by Django 3.0.5 on 2022-09-19 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('account', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActions',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('disliked_comments', models.ManyToManyField(related_name='disliked_by', to='comments.Comment')),
                ('disliked_posts', models.ManyToManyField(related_name='disliked_by', to='posts.Post')),
                ('liked_comments', models.ManyToManyField(related_name='liked_by', to='comments.Comment')),
                ('liked_posts', models.ManyToManyField(related_name='liked_by', to='posts.Post')),
                ('saved_comments', models.ManyToManyField(related_name='saved_by', to='comments.Comment')),
                ('saved_posts', models.ManyToManyField(related_name='saved_by', to='posts.Post')),
            ],
        ),
    ]
