# Generated by Django 3.0.5 on 2020-04-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='edited',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
